### ISSUE TITLE
Moving include.txt to gsa/data?

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/gatherer#18]
I'd be happy to add you as a contributor to gsa/data and host them here:
https://github.com/GSA/data/tree/master/dotgov-websites

Either as part of other-websites.csv or some other approach. But I think it would be great if we had a common CSV in a place we could both maintain, to use (and invite other contributions to) as part of our work.

**Comment by jsf9k** [comment]
I would be fine with that, and I think it makes a lot of sense.  @h-m-f-t do you have any objections or other thoughts?

**Comment by h-m-f-t** [comment]
None! I'm all for consolidating this.

**Comment by konklone** [comment]
I pulled in this data in https://github.com/GSA/data/pull/119 and merged it.

Would you all be up for relying on that file now instead of `include.txt`, and contributing further data to that file?
